language: node_js
node_js:
- '8'
install:
- npm install
script:
- npm run test
- npm run build

deploy:
  provider: npm
  email: TrdelnikSquad@cimpress.com
  skip_cleanup: true
  api_key:
    secure: SoeZiL3OoUbt+Wu3dCZ7or5dsebEWs5L+w/VCajkmE2aMiHkDtl5qHirlOZ8vUw+XS/3xii/ZoN1S3jv/W8D//xPQgA8VgWY9X6CZKVxoIjyJaHOVSo0s5W6cyZ25lBhM9GgpSKml5lLBpsfBuIi8T8HopDrXv6nt5CKKTn4o+3fS/Ymss5ae3TusBD6k1GYe+YSssRyR+2LNqsXJoUgB8A3pr5IQa2wkiZgRy0aq1vlT4FOvyfESSKmgqLaHGU52UfXJyoKqMC84OV1xEZLdmi5g3jnJiCTz5miRACVVTKZzmNqMHcLpzdgTkg4Bus/MBi0j75tOG/EK3nruUYfBRPu2uSTOda+Nsec+j1rBXfRUXn33DIKRtGrL7wRGV0Kgj3fDbWK1NesMGv6F7lPfAMUVt9v7Z/ocE9IwI9wiS+rY24NNlvJmDRIp4QlqIEe3gcy/2iwtBgKsTvKibFerf5kmmX/0epa/eYRCvtqvFhNuqivoghr3YMKrOaZoXQbYLrDjr0XAxYLFsEPRPlM1blhLM+3CJf5qIIb/4GAZihop3j0q5V9ncodpvfPHWGRYsgvM9bgSBFqlY7+A31D+1hd327VERImJtnVI59ySKoLDL+vKnlljwtAr3UYvrOcZqwMDPJ55lyhP6kZWF7/tjJXRU8VSSqDpF93yXjs9nw=
  on:
    branch: master
notifications:
  slack:
    secure: hcLcEUCHCua4mqVMhP1vXIsxaSJ9/u30xGIswPPg9iNdraL6V0CGbO9AUddP+Wpr+UEOxFhqA8aknZ6U0uDFg3Mi5h/IWerLSbFaJzuQtqoVWQuHFVkO4KgCRZy7Ihsk1U3e/JhsZIndmZ7/sMuN47K1naoEvahcbm7FrH8o7rUIFMrmHsGB7yIXtdbVcJINC8Ii5EN95ncGE3zOwVOBd5XMq8RYvxQWDEoyHxewJ3pkYW88Gss9Zjvs3SlOs3cq4jZyaB75DSHIZ1eeZ0A25/RANBdNH8BJcjtg4bMXk6KdG1t/9sn+KuHBU2EOwCIdRCzuuh2JXDA0wXh6oB7HDL484Kgq/rV/slEAVQXULMU/08txtZuf6DFDkVAB2E94SjzIWYUiOgzmbjEDbxs5SyuUJLu3Ciqua3Zpg2nDRQ4mvsOsAKW8CZxOapnM+29LlbNA4H0cfSrajLPwSt9LeWilFvoFvJ9KqfIzYDSxdoZFCMGfTOW9rlPL3zRWRYmn1rlQdCAoh751+wfvIXN5uU9sLWFBGt2jWqor0Lg4XtvFVGWCLtzfI0zh8aaBGihIVtsTCKeIC5mtFj6d83W+T4+WuV4niHnp2Xch9fVMLWThl+XuIDYRhG6cSrN8wmOZR+w6XJELBuzPhJ1qNGKxHJ9J5kgN5f04EUmTCvDmSVg=